(function(){
'use strict';
function el(id){return document.getElementById(id)}
function status(text,kind){var s=el('status'),bar=el('statusbar');if(s)s.textContent=text;if(bar)bar.className='statusbar '+(kind||'');try{parent.postMessage({source:'portal-panel',type:kind==='err'?'error':kind==='ok'?'ok':'loading',page:'dashboard_at1_historico.html',text:text},location.origin)}catch(ignore){}}
function diagnostics(){window.onerror=function(message,source,line,column){status('Erro V8.1: '+message+' · linha '+line+':'+column,'err');return false};window.addEventListener('unhandledrejection',function(event){var reason=event.reason;status('Falha assíncrona V8.1: '+((reason&&reason.message)||reason||'sem detalhe'),'err')})}
function loadOne(primary,fallback,label){return new Promise(function(resolve,reject){function attempt(url,canFallback){status('V8.1 · Carregando '+label+'...');var script=document.createElement('script');script.src=url;script.async=false;script.onload=resolve;script.onerror=function(){script.remove();if(canFallback&&fallback)attempt(fallback,false);else reject(new Error('Não foi possível carregar '+label))};document.head.appendChild(script)}attempt(primary,true)})}
async function start(){diagnostics();status('AT1 rápido · Preparando bibliotecas...');try{await Promise.all([loadOne('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2','https://unpkg.com/@supabase/supabase-js@2','Supabase'),loadOne('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://unpkg.com/xlsx@0.18.5/dist/xlsx.full.min.js','Excel'),loadOne('https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js','https://unpkg.com/chart.js@4.4.1/dist/chart.umd.min.js','Chart.js'),loadOne('https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0','https://unpkg.com/chartjs-plugin-datalabels@2.2.0','rótulos'),loadOne('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js','https://unpkg.com/html2canvas@1.4.1/dist/html2canvas.min.js','PNG')]);await loadOne('./dashboard_at1_historico.app.js?v=1081',null,'aplicação AT1')}catch(error){status('Falha no boot: '+error.message,'err')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
