(function(){
'use strict';
const SUPABASE_URL='https://frxfoztyctrvsobbawmo.supabase.co';
const SUPABASE_KEY='sb_publishable_or6yc7T71Hpyajn9ctn1FA_BjsB6LhL';
const TABLE='diario_bordo_at1',LOCAL='at1_diario_bordo_cache_v3';
let sb=null,events=[],allExpanded=false,online=false;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const summary=v=>String(v).length>145?String(v).slice(0,145).trim()+'…':String(v);
const fmt=d=>{const [y,m,day]=String(d).split('-');return `${day}/${m}/${y}`};
const cityNow=()=>norm($('fCity')?.value||'BAGE');
const setStatus=(text,kind='')=>{const e=$('diaryStatus');if(e){e.className='diary-status '+kind;e.textContent=text}};
function cacheLoad(){try{return JSON.parse(localStorage.getItem(LOCAL)||'[]')}catch{return[]}}
function cacheSave(){localStorage.setItem(LOCAL,JSON.stringify(events))}
function currentPeriod(){const t=$('chartTitle')?.textContent||'',m=t.match(/(\d{2})\/(\d{4})/);return m?{month:+m[1],year:+m[2],days:new Date(+m[2],+m[1],0).getDate()}:null}
function inMonth(date,p){const [y,m]=date.split('-').map(Number);return y===p.year&&m===p.month}
function visibleEvents(){const p=currentPeriod(),c=cityNow();return p?events.filter(e=>e.city===c&&(inMonth(e.date,p)||inMonth(e.endDate,p)||e.date<`${p.year}-${String(p.month).padStart(2,'0')}-01`&&e.endDate>`${p.year}-${String(p.month).padStart(2,'0')}-${p.days}`)):[]}
function dayClamped(date,p){const [y,m,d]=date.split('-').map(Number);if(y<p.year||(y===p.year&&m<p.month))return 1;if(y>p.year||(y===p.year&&m>p.month))return p.days;return Math.max(1,Math.min(p.days,d))}
function renderMarkers(){const box=document.querySelector('.chartbox'),p=currentPeriod();if(!box||!p)return;let layer=box.querySelector('.diary-markers');if(!layer){layer=document.createElement('div');layer.className='diary-markers';box.appendChild(layer)}const list=visibleEvents();layer.innerHTML=list.map((e,i)=>{const d1=dayClamped(e.date,p),d2=dayClamped(e.endDate,p),same=d1===d2,left=((d1-.5)/p.days)*100, right=((d2-.5)/p.days)*100,mid=(left+right)/2,stem=76+(i%3)*40;if(same)return `<div class="diary-marker" style="left:${left}%;--event:${esc(e.color)};--stem:${stem}px" data-id="${esc(e.id)}"><span class="bubble">${esc(e.title)}</span><span class="stem"></span></div>`;return `<div class="diary-period" style="left:${left}%;width:${Math.max(1,right-left)}%;--event:${esc(e.color)};--period-bottom:${56+(i%3)*42}px" data-id="${esc(e.id)}"><span class="bubble">${esc(e.title)}</span></div>`}).join('');layer.querySelectorAll('[data-id]').forEach(m=>m.onclick=()=>openEvent(m.dataset.id))}
function openEvent(id){openModal();setTimeout(()=>{const a=document.querySelector('.diary-event[data-id="'+CSS.escape(id)+'"]');if(a){a.classList.add('expanded');a.scrollIntoView({behavior:'smooth',block:'center'});a.querySelector('.diary-link').textContent='RESUMIR'}},30)}
function render(){events.sort((a,b)=>a.city.localeCompare(b.city,'pt-BR')||a.date.localeCompare(b.date));const groups={};events.forEach(e=>{groups[e.city]??={};(groups[e.city][e.date]??=[]).push(e)});$('diaryList').innerHTML=events.length?Object.entries(groups).map(([city,dates])=>`<div class="diary-day"><div class="diary-day-title">CIDADE: ${esc(city)}</div>${Object.entries(dates).map(([d,arr])=>`<div class="diary-day-title">${fmt(d)}${arr.some(e=>e.endDate!==e.date)?' · período até '+fmt(arr.reduce((x,e)=>e.endDate>x?e.endDate:x,d)):''}</div>${arr.map(e=>`<article class="diary-event ${allExpanded?'expanded':''}" data-id="${esc(e.id)}"><div class="diary-event-top"><i class="diary-dot" style="background:${esc(e.color)}"></i><span class="diary-event-title">${esc(e.title)} · ${fmt(e.date)}${e.endDate!==e.date?' a '+fmt(e.endDate):''}</span><button class="diary-link" type="button">${allExpanded?'RESUMIR':'VER TUDO'}</button><button class="diary-delete" type="button">EXCLUIR</button></div><p class="diary-summary">${esc(summary(e.text))}</p><div class="diary-full">${esc(e.text)}</div></article>`).join('')}`).join('')}</div>`).join(''):'<div class="diary-empty">Nenhum evento cadastrado.</div>';
$('diaryList').querySelectorAll('.diary-link').forEach(b=>b.onclick=()=>{const a=b.closest('.diary-event');a.classList.toggle('expanded');b.textContent=a.classList.contains('expanded')?'RESUMIR':'VER TUDO'});$('diaryList').querySelectorAll('.diary-delete').forEach(b=>b.onclick=()=>removeEvent(b.closest('.diary-event').dataset.id));renderMarkers()}
async function connect(){events=cacheLoad();render();let tries=0;while(!window.supabase?.createClient&&tries++<100)await new Promise(r=>setTimeout(r,100));if(!window.supabase?.createClient){setStatus('Biblioteca Supabase indisponível; exibindo cache local.','diary-sync-warn');return}try{sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data,error}=await sb.from(TABLE).select('id,cidade,data,data_fim,titulo,conteudo,cor,created_at').order('cidade').order('data');if(error)throw error;events=(data||[]).map(x=>({id:String(x.id),city:norm(x.cidade),date:x.data,endDate:x.data_fim||x.data,title:x.titulo,text:x.conteudo,color:x.cor||'#0ea5e9'}));online=true;cacheSave();render();setStatus('Sincronização online ativa.','diary-sync-ok')}catch(e){console.error('Diário:',e);setStatus('Execute o SQL atualizado incluído no pacote. Cache local mantido.','diary-sync-warn')}}
async function addEvent(e){if(!online){setStatus('Inclusão indisponível até executar o SQL atualizado.','diary-sync-warn');return false}const payload={cidade:e.city,data:e.date,data_fim:e.endDate,titulo:e.title,conteudo:e.text,cor:e.color};const {data,error}=await sb.from(TABLE).insert(payload).select('id,cidade,data,data_fim,titulo,conteudo,cor').single();if(error){setStatus('Não foi possível salvar: '+error.message,'diary-sync-warn');return false}events.push({id:String(data.id),city:norm(data.cidade),date:data.data,endDate:data.data_fim||data.data,title:data.titulo,text:data.conteudo,color:data.cor||'#0ea5e9'});cacheSave();render();setStatus('Evento salvo para '+norm(data.cidade)+'.','diary-sync-ok');return true}
async function removeEvent(id){if(!confirm('Excluir este evento?')||!online)return;const {error}=await sb.from(TABLE).delete().eq('id',id);if(error){setStatus('Não foi possível excluir: '+error.message,'diary-sync-warn');return}events=events.filter(x=>x.id!==id);cacheSave();render()}
function openModal(){$('diaryModal').classList.add('show');$('diaryModal').setAttribute('aria-hidden','false')}
function closeModal(){$('diaryModal').classList.remove('show');$('diaryModal').setAttribute('aria-hidden','true')}
$('diaryOpen').onclick=openModal;$('diaryClose').onclick=closeModal;$('diaryModal').onclick=e=>{if(e.target===$('diaryModal'))closeModal()};
$('diaryForm').onsubmit=async e=>{e.preventDefault();const start=$('diaryDate').value,end=$('diaryEndDate').value;if(end<start){setStatus('A data final não pode ser anterior à inicial.','diary-sync-warn');return}const ok=await addEvent({city:cityNow(),date:start,endDate:end,title:$('diaryEvent').value.trim(),text:$('diaryText').value.trim(),color:$('diaryColor').value});if(ok){e.target.reset();const today=new Date().toISOString().slice(0,10);$('diaryDate').value=$('diaryEndDate').value=today;$('diaryColor').value='#0ea5e9'}};
$('diaryToggleAll').onclick=()=>{allExpanded=!allExpanded;$('diaryToggleAll').textContent=allExpanded?'RESUMIR TODOS':'EXPANDIR TODOS';render()};
const today=new Date().toISOString().slice(0,10);$('diaryDate').value=$('diaryEndDate').value=today;$('diaryDate').onchange=()=>{if($('diaryEndDate').value<$('diaryDate').value)$('diaryEndDate').value=$('diaryDate').value};$('fCity')?.addEventListener('change',()=>setTimeout(renderMarkers,0));new MutationObserver(renderMarkers).observe($('chartTitle'),{childList:true,subtree:true});window.addEventListener('resize',renderMarkers);connect();
})();
