(function(){
'use strict';
const SUPABASE_URL='https://frxfoztyctrvsobbawmo.supabase.co';
const SUPABASE_KEY='sb_publishable_or6yc7T71Hpyajn9ctn1FA_BjsB6LhL';
const TABLE='diario_bordo_at1', LOCAL='at1_diario_bordo_cache_v2';
let sb=null,events=[],allExpanded=false,online=false;
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const summary=v=>String(v).length>145?String(v).slice(0,145).trim()+'…':String(v);
const fmt=d=>{const [y,m,day]=String(d).split('-');return `${day}/${m}/${y}`};
const setStatus=(text,kind='')=>{const e=$('diaryStatus');if(e){e.className='diary-status '+kind;e.textContent=text}};
function cacheLoad(){try{return JSON.parse(localStorage.getItem(LOCAL)||'[]')}catch{return[]}}
function cacheSave(){localStorage.setItem(LOCAL,JSON.stringify(events))}
function currentPeriod(){const t=$('chartTitle')?.textContent||'';const m=t.match(/(\d{2})\/(\d{4})/);return m?{month:+m[1],year:+m[2]}:null}
function markerEvents(){const p=currentPeriod();return p?events.filter(e=>{const [y,m]=e.date.split('-').map(Number);return y===p.year&&m===p.month}):[]}
function renderMarkers(){const box=document.querySelector('.chartbox');if(!box)return;let layer=box.querySelector('.diary-markers');if(!layer){layer=document.createElement('div');layer.className='diary-markers';box.appendChild(layer)}const list=markerEvents();layer.innerHTML=list.map((e,i)=>{const day=+e.date.slice(-2),left=((day-.5)/31)*100,stem=70+(i%3)*42;return `<div class="diary-marker" style="left:${left}%;--event:${esc(e.color)};--stem:${stem}px" data-id="${esc(e.id)}"><span class="bubble">${esc(e.title)}</span><span class="stem"></span></div>`}).join('');layer.querySelectorAll('.diary-marker').forEach(m=>m.onclick=()=>{openModal();setTimeout(()=>{const a=document.querySelector('.diary-event[data-id="'+CSS.escape(m.dataset.id)+'"]');if(a){a.classList.add('expanded');a.scrollIntoView({behavior:'smooth',block:'center'});a.querySelector('.diary-link').textContent='RESUMIR'}},30)})}
function render(){events.sort((a,b)=>a.date.localeCompare(b.date));const groups={};events.forEach(e=>(groups[e.date]??=[]).push(e));$('diaryList').innerHTML=events.length?Object.entries(groups).map(([d,arr])=>`<div class="diary-day"><div class="diary-day-title">${fmt(d)} · ${arr.length} evento(s)</div>${arr.map(e=>`<article class="diary-event ${allExpanded?'expanded':''}" data-id="${esc(e.id)}"><div class="diary-event-top"><i class="diary-dot" style="background:${esc(e.color)}"></i><span class="diary-event-title">${esc(e.title)}</span><button class="diary-link" type="button">${allExpanded?'RESUMIR':'VER TUDO'}</button><button class="diary-delete" type="button">EXCLUIR</button></div><p class="diary-summary">${esc(summary(e.text))}</p><div class="diary-full">${esc(e.text)}</div></article>`).join('')}</div>`).join(''):'<div class="diary-empty">Nenhum evento cadastrado.</div>';
$('diaryList').querySelectorAll('.diary-link').forEach(b=>b.onclick=()=>{const a=b.closest('.diary-event');a.classList.toggle('expanded');b.textContent=a.classList.contains('expanded')?'RESUMIR':'VER TUDO'});
$('diaryList').querySelectorAll('.diary-delete').forEach(b=>b.onclick=()=>removeEvent(b.closest('.diary-event').dataset.id));renderMarkers()}
async function connect(){events=cacheLoad();render();let tries=0;while(!window.supabase?.createClient&&tries++<100)await new Promise(r=>setTimeout(r,100));if(!window.supabase?.createClient){setStatus('Biblioteca Supabase indisponível; exibindo cache local.','diary-sync-warn');return}try{sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data,error}=await sb.from(TABLE).select('id,data,titulo,conteudo,cor,created_at').order('data',{ascending:true}).order('created_at',{ascending:true});if(error)throw error;events=(data||[]).map(x=>({id:String(x.id),date:x.data,title:x.titulo,text:x.conteudo,color:x.cor||'#0ea5e9'}));online=true;cacheSave();render();setStatus('Sincronização online ativa.','diary-sync-ok')}catch(e){console.error('Diário:',e);setStatus('Tabela do Diário indisponível; execute o SQL incluído no pacote. Cache local mantido.','diary-sync-warn')}}
async function addEvent(e){if(!online){setStatus('Inclusão online indisponível. Configure a tabela do Supabase usando o SQL do pacote.','diary-sync-warn');return}const payload={data:e.date,titulo:e.title,conteudo:e.text,cor:e.color};const {data,error}=await sb.from(TABLE).insert(payload).select('id,data,titulo,conteudo,cor,created_at').single();if(error){setStatus('Não foi possível salvar: '+error.message,'diary-sync-warn');return}events.push({id:String(data.id),date:data.data,title:data.titulo,text:data.conteudo,color:data.cor||'#0ea5e9'});cacheSave();render();setStatus('Evento salvo no Supabase.','diary-sync-ok')}
async function removeEvent(id){if(!confirm('Excluir este evento?'))return;if(!online){setStatus('Exclusão online indisponível.','diary-sync-warn');return}const {error}=await sb.from(TABLE).delete().eq('id',id);if(error){setStatus('Não foi possível excluir: '+error.message,'diary-sync-warn');return}events=events.filter(x=>x.id!==id);cacheSave();render();setStatus('Evento excluído.','diary-sync-ok')}
function openModal(){$('diaryModal').classList.add('show');$('diaryModal').setAttribute('aria-hidden','false')}
function closeModal(){$('diaryModal').classList.remove('show');$('diaryModal').setAttribute('aria-hidden','true')}
$('diaryOpen').onclick=openModal;$('diaryClose').onclick=closeModal;$('diaryModal').onclick=e=>{if(e.target===$('diaryModal'))closeModal()};
$('diaryForm').onsubmit=e=>{e.preventDefault();addEvent({date:$('diaryDate').value,title:$('diaryEvent').value.trim(),text:$('diaryText').value.trim(),color:$('diaryColor').value}).then(()=>{if(online){e.target.reset();$('diaryDate').value=new Date().toISOString().slice(0,10);$('diaryColor').value='#0ea5e9'}})};
$('diaryToggleAll').onclick=()=>{allExpanded=!allExpanded;$('diaryToggleAll').textContent=allExpanded?'RESUMIR TODOS':'EXPANDIR TODOS';render()};
$('diaryDate').value=new Date().toISOString().slice(0,10);new MutationObserver(renderMarkers).observe($('chartTitle'),{childList:true,subtree:true});window.addEventListener('resize',renderMarkers);connect();
})();