(function(){
'use strict';
const $=id=>document.getElementById(id);
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtInt=v=>Number(v||0).toLocaleString('pt-BR');
const fmtPct=(v,d=2)=>Number(v||0).toFixed(d).replace('.',',')+'%';
const SUPABASE_URL='https://frxfoztyctrvsobbawmo.supabase.co';
const SUPABASE_KEY='sb_publishable_or6yc7T71Hpyajn9ctn1FA_BjsB6LhL';
const BUCKET='bases-tecnico';
const CURRENT_FOLDER='atual';
const CURRENT_NAME='at1.xlsx';
const CURRENT_PATH=CURRENT_FOLDER+'/'+CURRENT_NAME;
const HISTORY_FOLDER='historico';
const HISTORY_RE=/^dashboard_at1_historico_(\d{4})\.(\d{2})\.xlsx$/i;
const REFRESH_MS=5*60*1000;
const METAS={TOTAL:.024,GPON:.015,HFC:.025,HIBRIDO:.035};
let sb=null,chart=null,refreshTimer=null;
let state={analitico:[],base:[],city:'BAGE',type:'TOTAL',start:'',end:'',node:'TODOS',baixa:'TODOS',file:null,sourceKind:'current',catalog:[]};
function postPortal(type,text){try{parent.postMessage({source:'portal-panel',type,page:'dashboard_at1_historico.html',text},location.origin)}catch(_){}}
function setStatus(text,kind=''){if($('status'))$('status').textContent=text;if($('statusbar'))$('statusbar').className='statusbar '+kind;postPortal(kind==='err'?'error':kind==='ok'?'ok':'loading',text)}
function humanError(e){const raw=String(e?.message||e||'Erro desconhecido');if(/401|jwt|unauthorized|session/i.test(raw))return'Sessão não autorizada pelo Supabase. Entre novamente pelo portal.';if(/403|row-level|rls|policy/i.test(raw))return'Acesso negado pela política SELECT do Storage para o bucket '+BUCKET+'.';if(/404|not found|object not found/i.test(raw))return'Objeto não encontrado no bucket '+BUCKET+'. Caminho solicitado: '+(state.file||CURRENT_PATH)+'.';return raw}
function timeout(promise,ms,label){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Tempo excedido em '+label)),ms))])}
function getField(r,names){const keys=Object.keys(r||{});for(const name of names){const k=keys.find(x=>norm(x)===norm(name));if(k!==undefined)return r[k]}return''}
function num(v){if(v==null||v==='')return 0;if(typeof v==='number')return v;let s=String(v).trim().replace(/\s/g,'').replace('%','');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');return Number(s)||0}
function mk(y,m,d){return{y,m,d,key:`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}}
function dateParts(v){if(v==null||v==='')return null;if(v instanceof Date&&!isNaN(v))return mk(v.getFullYear(),v.getMonth()+1,v.getDate());if(typeof v==='number'&&!isNaN(v)){const d=new Date(Math.round((v-25569)*864e5));return mk(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate())}let s=String(v).trim(),m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);if(m)return mk(+m[1],+m[2],+m[3]);m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);if(m)return mk(+m[3],+m[2],+m[1]);const d=new Date(s);return isNaN(d)?null:mk(d.getFullYear(),d.getMonth()+1,d.getDate())}
function city(r){return norm(getField(r,['MUNICIPIO','MUNICÍPIO','CIDADE','CIDADE BASE']))}
function node(r){return String(getField(r,['CD_NODE','NODE'])).trim()}
function baixa(r){return String(getField(r,['CD_BAIXA','CODIGO_BAIXA','CÓDIGO DE BAIXA','COD BAIXA'])).trim()}
function tipo(r){const v=norm(getField(r,['DSC_SEG_PRODUTO','DSC_SEGMENTACAO','TECNOLOGIA','TECNINOLOGIA','TECNILOGIA','PRODUTO','TIPO_AT1','NM_TECNOLOGIA','NM_TIPO_TECNOLOGIA']));if(v.includes('GPON'))return'GPON';if(v.includes('HFC'))return'HFC';if(v.includes('HIBR'))return'HIBRIDO';if(v.includes('TOTAL'))return'TOTAL';return v}
function statusOS(r){return norm(getField(r,['NM_STATUS_OS']))}
function expurgo(r){return norm(getField(r,['EXPURGO_AT1']))}
function generated(r){return dateParts(getField(r,['DATA','Data_nota','DATA_NOTA','DT_ABERTURA']))}
function executed(r){return dateParts(getField(r,['DT_FIM_EXECUCAO']))}
function rowDate(r){return generated(r)||executed(r)}
function isAT1(r){return statusOS(r)==='EXECUTADA'&&expurgo(r)==='NAO'}
function isG1(r){return['EXECUTADA','CANCELADA'].includes(statusOS(r))}
function matches(r,detail=true){const d=rowDate(r);return city(r)===state.city&&(state.type==='TOTAL'||tipo(r)===state.type)&&(!detail||((!state.start||d?.key>=state.start)&&(!state.end||d?.key<=state.end)&&(state.node==='TODOS'||node(r)===state.node)&&(state.baixa==='TODOS'||baixa(r)===state.baixa)))}
function baseValue(){const rows=state.base.filter(r=>city(r)===state.city);for(const r of rows){const keys=Object.keys(r),key=state.type==='TOTAL'?keys.find(k=>norm(k)==='TOTAL'||norm(k).includes('BASE TOTAL')):keys.find(k=>norm(k).includes(state.type));if(key&&num(r[key])>0)return num(r[key])}const infos=rows.map(r=>({tech:tipo(r),v:num(getField(r,['BASE','BASE CLIENTE','BASE_CLIENTE','QTD','CLIENTE']))})).filter(x=>x.v>0);if(state.type==='TOTAL'){const t=infos.find(x=>x.tech==='TOTAL');if(t)return t.v;const parts=infos.filter(x=>['GPON','HFC','HIBRIDO'].includes(x.tech));if(parts.length)return parts.reduce((a,x)=>a+x.v,0)}return infos.find(x=>x.tech===state.type)?.v||infos.find(x=>x.tech==='TOTAL')?.v||Math.max(0,...infos.map(x=>x.v))}
function period(rows){const ds=rows.map(rowDate).filter(Boolean).sort((a,b)=>a.key.localeCompare(b.key));const p=ds.at(-1)||mk(new Date().getFullYear(),new Date().getMonth()+1,1);return{y:p.y,m:p.m,days:new Date(p.y,p.m,0).getDate(),last:Math.max(1,...ds.filter(x=>x.y===p.y&&x.m===p.m).map(x=>x.d))}}
function fillSelect(id,values,current,all){const e=$(id);e.innerHTML=`<option value="TODOS">${all}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');e.value=values.includes(current)?current:'TODOS';return e.value}
function populate(){const cities=[...new Set(state.analitico.map(city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));$('fCity').innerHTML=cities.map(v=>`<option>${esc(v)}</option>`).join('');if(!cities.includes(state.city))state.city=cities[0]||'BAGE';$('fCity').value=state.city;$('fType').value=state.type;const baseRows=state.analitico.filter(r=>city(r)===state.city&&(state.type==='TOTAL'||tipo(r)===state.type));state.node=fillSelect('fNode',[...new Set(baseRows.map(node).filter(Boolean))].sort(),state.node,'TODOS OS NODES');state.baixa=fillSelect('fBaixa',[...new Set(baseRows.filter(r=>state.node==='TODOS'||node(r)===state.node).map(baixa).filter(Boolean))].sort(),state.baixa,'TODOS OS CÓDIGOS');$('fStart').value=state.start;$('fEnd').value=state.end}
function top(rows,getter,dateGetter,p,limit=20,only){const map=new Map();for(const r of rows){if(only&&!only(r))continue;const k=getter(r),d=dateGetter(r)||rowDate(r);if(!k||!d||d.y!==p.y||d.m!==p.m)continue;if(!map.has(k))map.set(k,{label:k,total:0,days:{}});const o=map.get(k);o.total++;o.days[d.d]=(o.days[d.d]||0)+1}return[...map.values()].sort((a,b)=>b.total-a.total||a.label.localeCompare(b.label)).slice(0,limit)}
function heat(id,label,items,p,total){let h=`<table class="heat"><thead><tr><th>${label}</th>`;for(let d=1;d<=p.days;d++)h+=`<th>${d}</th>`;h+='<th>TOTAL</th><th>%</th></tr></thead><tbody>';for(const x of items){h+=`<tr><td class="label">${esc(x.label)}</td>`;for(let d=1;d<=p.days;d++){const v=x.days[d]||0,c=v===0?'c0':v===1?'c1':v<=3?'c2':v<=5?'c3':'c4';h+=`<td class="${c}">${v||''}</td>`}h+=`<td>${x.total}</td><td>${fmtPct(total?x.total/total*100:0)}</td></tr>`}if(!items.length)h+=`<tr><td colspan="${p.days+3}">Sem dados para o filtro selecionado.</td></tr>`;$(id).innerHTML=h+'</tbody></table>'}
function render(){populate();const rows=state.analitico.filter(r=>matches(r,true)),all=state.analitico.filter(r=>matches(r,false)),p=period(all.length?all:rows),base=baseValue(),meta=METAS[state.type]??METAS.TOTAL,current=state.sourceKind==='current',divisor=current?p.last:p.days,exec=rows.filter(isAT1).length,g1=rows.filter(isG1).length,ger=rows.length,at1=base?(current?exec/divisor*p.days/base*100:exec/base*100):0,g1p=base?(current?g1/divisor*p.days/base*100:g1/base*100):0;
$('kAt1').textContent=fmtPct(at1);$('kG1').textContent=fmtPct(g1p);$('kExec').textContent=fmtInt(exec);$('kGer').textContent=fmtInt(ger);$('kBase').textContent=fmtInt(base);$('kMeta').textContent=fmtPct(meta*100,1);$('mReg').textContent=fmtInt(rows.length);$('mNodes').textContent=fmtInt(new Set(rows.map(node).filter(Boolean)).size);$('mBaixas').textContent=fmtInt(new Set(rows.map(baixa).filter(Boolean)).size);$('mAt1').textContent=fmtInt(exec);
const labels=Array.from({length:p.days},(_,i)=>String(i+1)),ex=Array(p.days).fill(0),ge=Array(p.days).fill(0);for(const r of rows){const ed=executed(r),gd=rowDate(r);if(isAT1(r)&&ed&&ed.y===p.y&&ed.m===p.m)ex[ed.d-1]++;if(gd&&gd.y===p.y&&gd.m===p.m)ge[gd.d-1]++}let ac=0;const proj=ex.map((v,i)=>{ac+=v;return base?ac/(i+1)*p.days/base*100:0});if(chart)chart.destroy();Chart.register(ChartDataLabels);chart=new Chart($('chart'),{data:{labels,datasets:[{type:'bar',label:'VT EXECUTADA',data:ex,backgroundColor:ex.map(v=>v<=base*meta/p.days?'#16803a':'#d00000'),yAxisID:'y'},{type:'line',label:'VT GERADA',data:ge,borderColor:'#f79009',borderDash:[6,5],pointRadius:2,yAxisID:'y'},{type:'line',label:'PROJEÇÃO',data:proj,borderColor:'#101828',borderWidth:3,pointRadius:0,yAxisID:'p'}]},options:{maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'},datalabels:{color:'#344054',anchor:'end',align:'top',formatter:(v,c)=>v?(c.dataset.yAxisID==='p'?fmtPct(v):fmtInt(v)):''}},scales:{y:{beginAtZero:true},p:{position:'right',grid:{drawOnChartArea:false},ticks:{callback:v=>v+'%'}}}}});$('chartTitle').textContent=`Evolução diária - ${state.city} / ${state.type} - ${String(p.m).padStart(2,'0')}/${p.y}`;
const map=new Map();for(const r of rows){const n=node(r)||'-',b=baixa(r)||'-',k=n+'|'+b;if(!map.has(k))map.set(k,{n,b,total:0,at1:0,g1:0});const o=map.get(k);o.total++;if(isAT1(r))o.at1++;if(isG1(r))o.g1++}let h='<table><thead><tr><th>NODE</th><th>CÓD. BAIXA</th><th>TOTAL</th><th>AT1</th><th>G1</th></tr></thead><tbody>';for(const o of[...map.values()].sort((a,b)=>b.total-a.total).slice(0,30))h+=`<tr><td>${esc(o.n)}</td><td>${esc(o.b)}</td><td>${o.total}</td><td>${o.at1}</td><td>${o.g1}</td></tr>`;$('detail').innerHTML=h+(map.size?'':'<tr><td colspan="5">Sem dados.</td></tr>')+'</tbody></table>';heat('nodeHeat','NODE',top(rows,node,executed,p,20,isAT1),p,exec);heat('baixaHeat','CÓD. BAIXA',top(rows,baixa,rowDate,p,20),p,ger);const gap=at1-meta*100,tn=top(rows,node,executed,p,1,isAT1)[0],tb=top(rows,baixa,rowDate,p,1)[0];$('insights').innerHTML=`<ul><li>AT1 ${current?'projetado':'fechado'}: <b>${fmtPct(at1)}</b>; meta: <b>${fmtPct(meta*100,1)}</b>; diferença: <b>${fmtPct(Math.abs(gap))} p.p. ${gap>0?'acima':'abaixo'}</b>.</li><li>G1 ${current?'projetado':'fechado'}: <b>${fmtPct(g1p)}</b>. Base cliente: <b>${fmtInt(base)}</b>.</li><li>Arquivo: <b>${esc(state.file)}</b>.</li><li>Top NODE: <b>${esc(tn?.label||'-')}</b>. Top código de baixa: <b>${esc(tb?.label||'-')}</b>.</li></ul>`}
function createClient(){if(!window.supabase?.createClient)throw new Error('Biblioteca Supabase não carregou.');return window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}})}
async function listFolder(folder){const result=await timeout(sb.storage.from(BUCKET).list(folder,{limit:1000,offset:0,sortBy:{column:'name',order:'asc'}}),15000,'listagem de '+folder);if(result.error)throw result.error;return(result.data||[]).filter(x=>x.id!==null&&/\.xlsx?$/i.test(x.name)).map(x=>({name:x.name,path:folder+'/'+x.name,folder,updated:x.updated_at||x.created_at||''}))}
function historyLabel(item){const m=item.name.match(HISTORY_RE);if(!m)return item.name;const names=['','JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];return`${names[Number(m[2])]||m[2]}/${m[1]} — ${item.name}`}
async function refreshCatalog(loadCurrent=false){setStatus('V5.1 · Consultando as pastas atual e historico...');const [currentFiles,historyFiles]=await Promise.all([listFolder(CURRENT_FOLDER),listFolder(HISTORY_FOLDER)]);const current=currentFiles.find(x=>norm(x.name)===norm(CURRENT_NAME));if(!current)throw new Error('O arquivo '+CURRENT_NAME+' não foi localizado dentro da pasta '+CURRENT_FOLDER+'. Encontrados: '+(currentFiles.map(x=>x.name).join(', ')||'nenhum Excel'));const history=historyFiles.filter(x=>HISTORY_RE.test(x.name)).sort((a,b)=>b.name.localeCompare(a.name));state.catalog=[{...current,kind:'current'},...history.map(x=>({...x,kind:'history'}))];const previous=$('sourceSelect').value||state.file||current.path,select=$('sourceSelect');select.innerHTML='';select.add(new Option('ATUAL — '+current.path,current.path));for(const item of history)select.add(new Option('HISTÓRICO — '+historyLabel(item),item.path));select.value=state.catalog.some(x=>x.path===previous)?previous:current.path;setStatus(`V5.1 · Caminho atual confirmado: ${current.path}; ${history.length} histórico(s).`,'ok');if(loadCurrent)await loadPath(current.path,'current');return{current,history}}
async function fetchWorkbook(path){const direct=await timeout(sb.storage.from(BUCKET).download(path,{}, {cache:'no-store'}),20000,'download de '+path);if(!direct.error&&direct.data)return direct.data.arrayBuffer();const signed=await timeout(sb.storage.from(BUCKET).createSignedUrl(path,120),15000,'URL assinada de '+path);if(signed.error||!signed.data?.signedUrl)throw direct.error||signed.error||new Error('Não foi possível acessar '+path);const response=await timeout(fetch(signed.data.signedUrl+(signed.data.signedUrl.includes('?')?'&':'?')+'_ts='+Date.now(),{cache:'no-store'}),20000,'transferência de '+path);if(!response.ok)throw new Error('HTTP '+response.status+' ao baixar '+path);return response.arrayBuffer()}
function findSheet(wb,names,index){const wanted=names.map(norm);return wb.SheetNames.find(n=>wanted.includes(norm(n)))||wb.SheetNames[index]||null}
async function loadPath(path,kind){if(!path)return;state.file=path;$('loadBtn').disabled=true;$('refreshBtn').disabled=true;setStatus('Baixando '+path+'...');try{const buf=await fetchWorkbook(path);if(!buf?.byteLength)throw new Error('Arquivo vazio: '+path);const wb=XLSX.read(buf,{type:'array',cellDates:true}),an=findSheet(wb,['ANALITICO','ANALÍTICO'],0),bn=findSheet(wb,['BASE','BASE CLIENTE','BASE_CLIENTE'],1);if(!an||!bn)throw new Error('Abas necessárias não encontradas. Disponíveis: '+wb.SheetNames.join(', '));const analitico=XLSX.utils.sheet_to_json(wb.Sheets[an],{defval:'',raw:true}),base=XLSX.utils.sheet_to_json(wb.Sheets[bn],{defval:'',raw:true});if(!analitico.length||!base.length)throw new Error('Planilha sem registros nas abas '+an+' / '+bn);state.analitico=analitico;state.base=base;state.file=path;state.sourceKind=kind||(path.startsWith(CURRENT_FOLDER+'/')?'current':'history');state.city='BAGE';state.type='TOTAL';state.start='';state.end='';state.node='TODOS';state.baixa='TODOS';render();$('updated').textContent='Carregado em '+new Date().toLocaleString('pt-BR');$('fileInfo').textContent=`Supabase: ${BUCKET}/${path} | Abas: ${an} e ${bn} | ${fmtInt(analitico.length)} registros`;setStatus('Base carregada com sucesso: '+path,'ok')}catch(e){console.error(e);setStatus('Falha: '+humanError(e),'err')}finally{$('loadBtn').disabled=false;$('refreshBtn').disabled=false}}
async function connect(){try{setStatus('V5.1 · Conectando ao Supabase...');sb=createClient();await refreshCatalog(true);if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(async()=>{try{const viewing=state.sourceKind==='current',cat=await refreshCatalog(false);if(viewing)await loadPath(cat.current.path,'current')}catch(e){setStatus('Atualização automática: '+humanError(e),'err')}},REFRESH_MS)}catch(e){console.error(e);setStatus('Falha V5.1: '+humanError(e),'err')}}
$('refreshBtn').onclick=()=>refreshCatalog(false).catch(e=>setStatus('Falha: '+humanError(e),'err'));
$('loadBtn').onclick=()=>{const path=$('sourceSelect').value,item=state.catalog.find(x=>x.path===path);loadPath(path,item?.kind||'history')};
$('fCity').onchange=e=>{state.city=e.target.value;state.node=state.baixa='TODOS';render()};$('fType').onchange=e=>{state.type=e.target.value;state.node=state.baixa='TODOS';render()};$('fStart').onchange=e=>{state.start=e.target.value;render()};$('fEnd').onchange=e=>{state.end=e.target.value;render()};$('fNode').onchange=e=>{state.node=e.target.value;state.baixa='TODOS';render()};$('fBaixa').onchange=e=>{state.baixa=e.target.value;render()};$('clearBtn').onclick=()=>{state.start=state.end='';state.node=state.baixa='TODOS';render()};$('pngBtn').onclick=async()=>{const c=await html2canvas($('dashboardRoot'),{scale:2,backgroundColor:'#f2f4f7'}),a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`dashboard_at1_${state.city}_${state.type}.png`;a.click()};
window.addEventListener('beforeunload',()=>refreshTimer&&clearInterval(refreshTimer));
setStatus('V5.1 · Aplicação carregada; usando atual/at1.xlsx.');
connect();
})();
