(function(){
'use strict';
const BUILD='11000';
function el(id){return document.getElementById(id)}
function status(text,kind){const s=el('status'),bar=el('statusbar');if(s)s.textContent=text;if(bar)bar.className='statusbar '+(kind||'');try{parent.postMessage({source:'portal-panel',type:kind==='err'?'error':kind==='ok'?'ok':'loading',page:'dashboard_at1_historico.html',text},location.origin)}catch(_){}}
function diagnostics(){window.onerror=function(message,source,line,column){status('Erro V11: '+message+' · linha '+line+':'+column,'err');return false};window.addEventListener('unhandledrejection',e=>status('Falha V11: '+((e.reason&&e.reason.message)||e.reason||'sem detalhe'),'err'))}
function loadOne(primary,fallback,label){return new Promise((resolve,reject)=>{let done=false;const finish=(ok,value)=>{if(done)return;done=true;clearTimeout(timer);ok?resolve(value):reject(value)};const timer=setTimeout(()=>finish(false,new Error('Tempo excedido ao carregar '+label)),20000);function attempt(url,canFallback){status('V11 · Carregando '+label+'...');const script=document.createElement('script');script.src=url;script.async=false;script.onload=()=>finish(true);script.onerror=()=>{script.remove();if(canFallback&&fallback)attempt(fallback,false);else finish(false,new Error('Não foi possível carregar '+label))};document.head.appendChild(script)}attempt(primary,true)})}
async function start(){diagnostics();status('V11 · Preparando bibliotecas...');try{await Promise.all([loadOne('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2','https://unpkg.com/@supabase/supabase-js@2','Supabase'),loadOne('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://unpkg.com/xlsx@0.18.5/dist/xlsx.full.min.js','Excel'),loadOne('https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js','https://unpkg.com/chart.js@4.4.1/dist/chart.umd.min.js','Chart.js'),loadOne('https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2.0','https://unpkg.com/chartjs-plugin-datalabels@2.2.0','rótulos'),loadOne('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js','https://unpkg.com/html2canvas@1.4.1/dist/html2canvas.min.js','PNG')]);await loadOne('./dashboard_at1_historico.app.js?v='+BUILD,null,'aplicação AT1')}catch(error){status('Falha no boot V11: '+error.message,'err')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
